version: "3.8"

services:

  # Install redpanda kafka-cluster
  redpanda:
    command:
      - redpanda
      - start
      - --smp
      - '1'
      - --reserve-memory
      - 0M
      - --overprovisioned
      - --node-id
      - '0'
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
    image: vectorized/redpanda
    container_name: redpanda
    ports:
      - 9092:9092
      - 29092:29092

  # Install member kafka-producer
  member-producer:
    build:
      context: ../producer
      dockerfile: ../producer/Dockerfile
    container_name: member-producer
    image: jwiegmann.de/member-producer
    ports:
      - 8080:8080
    depends_on:
      - redpanda

  # Install member kafka-consumer
  member-consumer:
    build:
      context: ../consumer
      dockerfile: ../consumer/Dockerfile
    container_name: member-consumer
    image: jwiegmann.de/member-consumer
    depends_on:
      - redpanda
      - member-producer